#!/usr/bin/env python
# -*- coding: UTF-8 -*-
"""Reads the output file generated by the following cProfile call:
python -m cProfile -o OUTPUT_FILE SCRIPT.py

and prints the results in the stdin.

Usage:

python printcProfile -l NUMBER_OF_LINES -s SORT_OPTION OUTPUT_FILE

Nicolas Valcarcel <nvalcarcel@gmail.com>"""

import argparse
import pstats


def print_stats(filename, sort='cumulative', lines=1.0):
    """Does the actual printing"""
    p = pstats.Stats(filename)
    p.strip_dirs().sort_stats(sort).print_stats(lines)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Print cProfile output')
    parser.add_argument('filename', metavar='filename',
                        help='cProfile run output file')
    parser.add_argument('-l', '--lines', type=int, metavar='#',
                        help='Number of lines to print')
    parser.add_argument('-s', '--sort', choices=['calls', 'cumulative', 'file',
                                                 'module', 'pcalls', 'line',
                                                 'name', 'nfl', 'stdname',
                                                 'time'],
                        default='cumulative',
                        help='sort method to use. (Default: cumulative)')
    args = parser.parse_args()
    print_stats(**vars(args))
